image: python:3.9-buster

stages:
  - style
  - quality
  - build
  - test
  - deploy

# style
flake8:
  stage: style
  script:
    - pip install --upgrade flake8==5
    - flake8 --exclude=_version.py rtctools_interface  
  tags:
    - gitlab-org-docker

# code quality
pylint:
  stage: quality
  script:
    - pip install -e .
    - pip install pylint
    - pylint rtctools_interface/optimization tests
  tags:
    - gitlab-org-docker

# test
test39:
  stage: test
  script:
    - pip install -e .
    - pip install pytest
    - pytest tests 
  tags:
    - gitlab-org-docker

build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - gitlab-org-docker

deploy:
  stage: deploy
  dependencies:
    - build
  script:
      - pip install -U twine
      - twine upload -u $PYPI_USER -p $PYPI_PASSWORD dist/*
  only:
      - tags
