image: python:3.9-buster

stages:
  - style
  - test

# style
flake8:
  stage: style
  script:
    - pip install --upgrade flake8==5
    - flake8 --exclude=_version.py rtctools_interface  
  tags:
    - docker
    - linux

# test
test39:
  stage: test
  script:
    - pip install -e .
    - pip install pytest
    - pytest tests 
  tags:
    - docker
    - linux
